# Generated by Django 4.1.3 on 2022-11-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('task', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, upload_to='app1/files/covers')),
            ],
        ),
    ]
